name: make-release
run-name: Make release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - run: make ci VERBOSE=1
        env:
          GH_TOKEN: ${{ github.token }}
